name: Full build
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

  workflow_dispatch:
    inputs:
      ref:
        required: true
        default: 'main'
        type: string
        description: 'branch / tag or commit id to build'
      artifact-retention:
        required: true
        default: 1
        type: number
        description: 'artifact retention time in days'
        
jobs:
  on_pull_request_check:
    name: Pull request (sanity checks)
    runs-on: [yocto-builder]
    container:
      image: linuxplswbuildcontainerregistry.azurecr.io/vaillant-neext/plsw-linux-tools-yocto-build-container/plsw-linux-tools-yocto-build-container:latest
      credentials:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    steps:
      - name: Init
        run: git config --global --add safe.directory '*'
        
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ secrets.MACHINE_USER_ACCESS_TOKEN }}
          submodules: false
          set-safe-directory: "*"

      - name: Check Commit Messages
        uses: Vaillant-NEEXT/plsw-linux-tools-shared-workflows/.github/actions/commit-message-check@main

      - name: Check Submodules
        uses: Vaillant-NEEXT/plsw-linux-tools-shared-workflows/.github/actions/submodule-check@main

  build-and-test:
    name: Build and test
    needs: on_pull_request_check
    uses: Vaillant-NEEXT/plsw-linux-tools-shared-workflows/.github/workflows/build_test_application.yml@main
    with:
      ref: ${{ github.event.pull_request.head.sha }}
      artifact-retention: 1
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      MACHINE_USER_ACCESS_TOKEN: ${{ secrets.MACHINE_USER_ACCESS_TOKEN }}
